/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.udea.musicus.gui;

/**
 *
 * @author twx
 */
public class PanelResumen extends javax.swing.JPanel {

    /**
     * Creates new form PanelResumen
     */
    public PanelResumen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelResultado = new javax.swing.JLabel();
        jLabelTextoPromedio = new javax.swing.JLabel();
        jButtonReiniciarNivel = new javax.swing.JButton();
        jButtonMenuPrincipal = new javax.swing.JButton();
        jButtonSiguienteNivel = new javax.swing.JButton();
        jScrollPaneTextAreaResumen = new javax.swing.JScrollPane();
        jTextAreaResumen = new javax.swing.JTextArea();
        jLabelValorPromedio = new javax.swing.JLabel();
        jLabelImagenPersonaje = new javax.swing.JLabel();
        jLabelTextoReconocimiento = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jLabelResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelResultado.setText("Texto resultado nivel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jLabelResultado, gridBagConstraints);

        jLabelTextoPromedio.setText("Promedio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jLabelTextoPromedio, gridBagConstraints);

        jButtonReiniciarNivel.setText("Reinicar nivel");
        jButtonReiniciarNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReiniciarNivelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jButtonReiniciarNivel, gridBagConstraints);

        jButtonMenuPrincipal.setText("Menu principal");
        jButtonMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuPrincipalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jButtonMenuPrincipal, gridBagConstraints);

        jButtonSiguienteNivel.setText("Siguiente nivel");
        jButtonSiguienteNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteNivelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jButtonSiguienteNivel, gridBagConstraints);

        jTextAreaResumen.setEditable(false);
        jTextAreaResumen.setColumns(20);
        jTextAreaResumen.setLineWrap(true);
        jTextAreaResumen.setRows(5);
        jTextAreaResumen.setWrapStyleWord(true);
        jScrollPaneTextAreaResumen.setViewportView(jTextAreaResumen);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jScrollPaneTextAreaResumen, gridBagConstraints);

        jLabelValorPromedio.setText("correctas / total");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jLabelValorPromedio, gridBagConstraints);

        jLabelImagenPersonaje.setText("imagen del personaje");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jLabelImagenPersonaje, gridBagConstraints);

        jLabelTextoReconocimiento.setText("Has ganado reconocimiento de personaje");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jLabelTextoReconocimiento, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReiniciarNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReiniciarNivelActionPerformed
//        jPanelNivel.remove(jPanelResultadoNivel);
//        jPanelNivel.add(jPanelPregunta);
//        pack();
    }//GEN-LAST:event_jButtonReiniciarNivelActionPerformed

    private void jButtonMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuPrincipalActionPerformed
//        jPanelNivel.remove(jPanelResultadoNivel);
//        jPanelNivel.setVisible(false);
//        jPanelInicio.setVisible(true);
//        pack();
    }//GEN-LAST:event_jButtonMenuPrincipalActionPerformed

    private void jButtonSiguienteNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteNivelActionPerformed
//        JOptionPane.showMessageDialog(this, "Aun no.");
    }//GEN-LAST:event_jButtonSiguienteNivelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMenuPrincipal;
    private javax.swing.JButton jButtonReiniciarNivel;
    private javax.swing.JButton jButtonSiguienteNivel;
    private javax.swing.JLabel jLabelImagenPersonaje;
    private javax.swing.JLabel jLabelResultado;
    private javax.swing.JLabel jLabelTextoPromedio;
    private javax.swing.JLabel jLabelTextoReconocimiento;
    private javax.swing.JLabel jLabelValorPromedio;
    private javax.swing.JScrollPane jScrollPaneTextAreaResumen;
    private javax.swing.JTextArea jTextAreaResumen;
    // End of variables declaration//GEN-END:variables
}
