/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.udea.musicus.gui;

/**
 *
 * @author mateo1235
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelNivel = new javax.swing.JPanel();
        buttonGroupRespuestas = new javax.swing.ButtonGroup();
        jPanelPregunta = new javax.swing.JPanel();
        jLabelTextoPregunta = new javax.swing.JLabel();
        jLabelImagenPregunta = new javax.swing.JLabel();
        jButtonEnviarRespuesta = new javax.swing.JButton();
        jPanelRespuestas = new javax.swing.JPanel();
        jRadioButtonRespuestaA = new javax.swing.JRadioButton();
        jRadioButtonRespuestaB = new javax.swing.JRadioButton();
        jRadioButtonRespuestaC = new javax.swing.JRadioButton();
        jRadioButtonRespuestaD = new javax.swing.JRadioButton();
        jPanelResultadoNivel = new javax.swing.JPanel();
        jLabelResultado = new javax.swing.JLabel();
        jLabelTextoPromedio = new javax.swing.JLabel();
        jButtonReiniciarNivel = new javax.swing.JButton();
        jButtonMenuPrincipal = new javax.swing.JButton();
        jButtonSiguienteNivel = new javax.swing.JButton();
        jScrollPaneTextAreaResumen = new javax.swing.JScrollPane();
        jTextAreaResumen = new javax.swing.JTextArea();
        jLabelValorPromedio = new javax.swing.JLabel();
        jLabelImagenPersonaje = new javax.swing.JLabel();
        jLabelTextoReconocimiento = new javax.swing.JLabel();
        jPanelInicio = new javax.swing.JPanel();
        jLabelTituloJuego = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jButtonIniciar = new javax.swing.JButton();
        jLabelNivel = new javax.swing.JLabel();
        jComboBoxNiveles = new javax.swing.JComboBox();

        jPanelNivel.setBorder(javax.swing.BorderFactory.createTitledBorder("Nivel n - Tema 'Nostrabamus'"));
        jPanelNivel.setLayout(new java.awt.GridBagLayout());

        jPanelPregunta.setBorder(javax.swing.BorderFactory.createTitledBorder("Pregunta m"));
        jPanelPregunta.setLayout(new java.awt.GridBagLayout());

        jLabelTextoPregunta.setText("¿Texto de la pregunta?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 5.0;
        gridBagConstraints.weighty = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanelPregunta.add(jLabelTextoPregunta, gridBagConstraints);

        jLabelImagenPregunta.setText("imagen pregunta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 5.0;
        gridBagConstraints.weighty = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanelPregunta.add(jLabelImagenPregunta, gridBagConstraints);

        jButtonEnviarRespuesta.setText("Enviar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanelPregunta.add(jButtonEnviarRespuesta, gridBagConstraints);

        jPanelRespuestas.setBorder(javax.swing.BorderFactory.createTitledBorder("Respuestas"));
        jPanelRespuestas.setLayout(new java.awt.GridBagLayout());

        buttonGroupRespuestas.add(jRadioButtonRespuestaA);
        jRadioButtonRespuestaA.setText("A. Texto Respuesta A");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanelRespuestas.add(jRadioButtonRespuestaA, gridBagConstraints);

        buttonGroupRespuestas.add(jRadioButtonRespuestaB);
        jRadioButtonRespuestaB.setText("B. Texto Respuesta B");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanelRespuestas.add(jRadioButtonRespuestaB, gridBagConstraints);

        buttonGroupRespuestas.add(jRadioButtonRespuestaC);
        jRadioButtonRespuestaC.setText("C. Texto Respuesta C");
        jRadioButtonRespuestaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRespuestaCActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanelRespuestas.add(jRadioButtonRespuestaC, gridBagConstraints);

        buttonGroupRespuestas.add(jRadioButtonRespuestaD);
        jRadioButtonRespuestaD.setText("D. Texto Respuesta D");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanelRespuestas.add(jRadioButtonRespuestaD, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 7.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanelPregunta.add(jPanelRespuestas, gridBagConstraints);

        jPanelResultadoNivel.setBorder(javax.swing.BorderFactory.createTitledBorder("Nivel n Terimado"));
        jPanelResultadoNivel.setLayout(new java.awt.GridBagLayout());

        jLabelResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelResultado.setText("Texto resultado nivel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanelResultadoNivel.add(jLabelResultado, gridBagConstraints);

        jLabelTextoPromedio.setText("Promedio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanelResultadoNivel.add(jLabelTextoPromedio, gridBagConstraints);

        jButtonReiniciarNivel.setText("Reinicar nivel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanelResultadoNivel.add(jButtonReiniciarNivel, gridBagConstraints);

        jButtonMenuPrincipal.setText("Menu principal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanelResultadoNivel.add(jButtonMenuPrincipal, gridBagConstraints);

        jButtonSiguienteNivel.setText("Siguiente nivel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanelResultadoNivel.add(jButtonSiguienteNivel, gridBagConstraints);

        jTextAreaResumen.setEditable(false);
        jTextAreaResumen.setColumns(20);
        jTextAreaResumen.setLineWrap(true);
        jTextAreaResumen.setRows(5);
        jTextAreaResumen.setWrapStyleWord(true);
        jScrollPaneTextAreaResumen.setViewportView(jTextAreaResumen);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanelResultadoNivel.add(jScrollPaneTextAreaResumen, gridBagConstraints);

        jLabelValorPromedio.setText("correctas / total");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanelResultadoNivel.add(jLabelValorPromedio, gridBagConstraints);

        jLabelImagenPersonaje.setText("imagen del personaje");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanelResultadoNivel.add(jLabelImagenPersonaje, gridBagConstraints);

        jLabelTextoReconocimiento.setText("Has ganado reconocimiento de personaje");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanelResultadoNivel.add(jLabelTextoReconocimiento, gridBagConstraints);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanelInicio.setLayout(new java.awt.GridBagLayout());

        jLabelTituloJuego.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloJuego.setText("MUSICUS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanelInicio.add(jLabelTituloJuego, gridBagConstraints);

        jLabelUsuario.setText("Usuario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanelInicio.add(jLabelUsuario, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanelInicio.add(jTextFieldUsuario, gridBagConstraints);

        jButtonIniciar.setText("Iniciar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanelInicio.add(jButtonIniciar, gridBagConstraints);

        jLabelNivel.setText("Nivel:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanelInicio.add(jLabelNivel, gridBagConstraints);

        jComboBoxNiveles.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione...", "Nivel 1", "Nivel 2", "Nivel 3" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanelInicio.add(jComboBoxNiveles, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanelInicio, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonRespuestaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRespuestaCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonRespuestaCActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupRespuestas;
    private javax.swing.JButton jButtonEnviarRespuesta;
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JButton jButtonMenuPrincipal;
    private javax.swing.JButton jButtonReiniciarNivel;
    private javax.swing.JButton jButtonSiguienteNivel;
    private javax.swing.JComboBox jComboBoxNiveles;
    private javax.swing.JLabel jLabelImagenPersonaje;
    private javax.swing.JLabel jLabelImagenPregunta;
    private javax.swing.JLabel jLabelNivel;
    private javax.swing.JLabel jLabelResultado;
    private javax.swing.JLabel jLabelTextoPregunta;
    private javax.swing.JLabel jLabelTextoPromedio;
    private javax.swing.JLabel jLabelTextoReconocimiento;
    private javax.swing.JLabel jLabelTituloJuego;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabelValorPromedio;
    private javax.swing.JPanel jPanelInicio;
    private javax.swing.JPanel jPanelNivel;
    private javax.swing.JPanel jPanelPregunta;
    private javax.swing.JPanel jPanelRespuestas;
    private javax.swing.JPanel jPanelResultadoNivel;
    private javax.swing.JRadioButton jRadioButtonRespuestaA;
    private javax.swing.JRadioButton jRadioButtonRespuestaB;
    private javax.swing.JRadioButton jRadioButtonRespuestaC;
    private javax.swing.JRadioButton jRadioButtonRespuestaD;
    private javax.swing.JScrollPane jScrollPaneTextAreaResumen;
    private javax.swing.JTextArea jTextAreaResumen;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
